// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqyJpSvybEYk32Ez_-9JXyPnhoogLvjVY',
    appId: '1:1038550523195:web:653423fb763fc8c667ab1e',
    messagingSenderId: '1038550523195',
    projectId: 'spadesgame-1d6ba',
    authDomain: 'spadesgame-1d6ba.firebaseapp.com',
    databaseURL: 'https://spadesgame-1d6ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spadesgame-1d6ba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM3-wCdq3ph3cJ49PppBaPKYXrETO1DW4',
    appId: '1:1038550523195:android:921a0e863ed97c9e67ab1e',
    messagingSenderId: '1038550523195',
    projectId: 'spadesgame-1d6ba',
    databaseURL: 'https://spadesgame-1d6ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spadesgame-1d6ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrwfIaWlJR-fRDT4t0ft9803K2rot_6P4',
    appId: '1:1038550523195:ios:f90300bd3d3ab16b67ab1e',
    messagingSenderId: '1038550523195',
    projectId: 'spadesgame-1d6ba',
    databaseURL: 'https://spadesgame-1d6ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spadesgame-1d6ba.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrwfIaWlJR-fRDT4t0ft9803K2rot_6P4',
    appId: '1:1038550523195:ios:f90300bd3d3ab16b67ab1e',
    messagingSenderId: '1038550523195',
    projectId: 'spadesgame-1d6ba',
    databaseURL: 'https://spadesgame-1d6ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spadesgame-1d6ba.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqyJpSvybEYk32Ez_-9JXyPnhoogLvjVY',
    appId: '1:1038550523195:web:a13bc4fefe59a82367ab1e',
    messagingSenderId: '1038550523195',
    projectId: 'spadesgame-1d6ba',
    authDomain: 'spadesgame-1d6ba.firebaseapp.com',
    databaseURL: 'https://spadesgame-1d6ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spadesgame-1d6ba.firebasestorage.app',
  );
}
